

### register

 
POST http://localhost:4000/evaluation
Content-Type:  application/json

{
	"all" : true
}
### some

POST http://localhost:4000/evaluation
Content-Type:  application/json

{
	"all" : false,
	"ids" :  [
  { "_id": "664217adf8b1cf7706c8c48c" },
  { "_id": "6642184df8b1cf7706c8c48d" }
]
}
 
### fill eval

POST http://localhost:4000/evaluation/eval/664217adf8b1cf7706c8c48c
Content-Type:  application/json

{
		"student_id": "664223823276240b7fe9136a",
		"course_id": "664223823276240b7fe9136a",
		"professionalismI": 5,
		"knowledgeI": 5,
		"communicationI": 5,
		"organizationI": 5,
		"responsivenessI": 5,
		"teaching_styleI": 5
}
### get eval
GET http://localhost:4000/evaluation/664217adf8b1cf7706c8c48c
Content-Type:  application/json

  


 
POST http://localhost:3000/attendance/new
Content-Type:  application/json

{
    "course_name":"Maths",
	"instructor_id":"6627f3543267383b7d6046e6",
	"date":"2024-09-09",
	"attendance":[
		{
			"student_id":"66279e0dda5951ab06556ed7",
			"status":"Present"
			
},
		{
				"student_id":"66279e2fda5951ab06556ed8",
			"status":"Present"
			
		}
	]
}
### Get Instructor Attendance
POST http://localhost:3000/attendance/instructor
Content-Type:  application/json

{
   	"course_id":"662802ac728d90164b677588",
	"instructor_id":"6627f3543267383b7d6046e6"
}

### edit
PATCH  http://localhost:3000/attendance/attendance
Content-Type:  application/json

{
	"attendance":[
		{
			"attendance_id":"662e2e61edf7345bc7c766bc",
			"attendances":[
				{
					"status":"Present",
					"date" : "2024-09-09"
				},
				{
					"status":"Absent",
					"date" : "2024-09-10"
				}
			]
			
},
		{
			"attendance_id":"662e49eee52af96417d47607",
			"attendances":[
				{
					"status":"Absent",
					"date" : "2024-09-09"
				},
				{
					"status":"Absent",
					"date" : "2024-09-10"
				}
			]
			
		}
	]
}
 
