POST http://localhost:5000/notification 
Content-Type:  application/json

{"data" : {
 "srecipient": ["sodrinarte@gufum.com" , "bajakes638@jadsys.com"],
 "message" : "this is the  new m",
 "type" : "blaaa"
} , "name" : "student" , 
     "dept_id" : "663a8a581f5ac9b89475633m"}
### notification spec
POST http://localhost:5000/notification 
Content-Type:  application/json

{"data" : {
 "srecipient": ["663a8a581f5ac9b89475633c"],
 "message" : "this is the  new m",
 "type" : "blaaa"
} , "stud_id" : "663a8a581f5ac9b89475633c"}
### get notification 
GET http://localhost:5000/notification/sodrinarte@gufum.com
Content-Type:  application/json
 
### delete notification
DELETE  http://localhost:4000/notification/6661a8987a9682152c3c0e12
Content-Type:  application/json
 
### get notification 
GET http://localhost:5000/notification/notify?id=sodrinarte@gufum.com&isRead=false
Content-Type:  application/json

### get check 
GET http://localhost:4000/notification/hi
Content-Type:  application/json

### get check 
POST http://localhost:5000/notification/true
Content-Type:  application/json

{     "email" : "sodrinarte@gufum.com",
     "data" : [
          "66661227a9d9eb6212f8fc4e"
     ]
}


# ### create rooms 
# POST http://localhost:4000/rooms/createRooms
# Content-Type:  application/json

# {
#   "block":"65",
#   "rooms":10,
#   "start_with":101
 
# }

# ### get rooms 
# GET  http://localhost:4000/rooms
# Content-Type:  application/json



# ### get spc
# GET  http://localhost:4000/rooms/663a8a581f5ac9b89475633a
# Content-Type:  application/json
 

# ### update a room (with put or patch)
# PATCH http://localhost:4000/rooms/663a8a581f5ac9b894756339
# Content-Type:  application/json

# {
#   "block": "c"	
# }
# ###
# DELETE  http://localhost:4000/rooms/663a8a581f5ac9b894756339
# Content-Type:  application/json
 

 
 
 