export const studentSideBarData = [
  {
    index: 0,
    label: "Dashboard",
    icon: "home",
    link: "/",
    role: "",
  },
  {
    index: 1,
    label: "Courses",
    icon: "book",
    link: "/myCourses",
    role: "",
  },
  {
    index: 2,
    label: "Registration",
    icon: "user",
    link: "/myRegistration",
    role: "",
  },
  {
    index: 3,
    label: "Grades",
    icon: "student",
    link: "/myGrades",
    role: "",
  },
  {
    index: 4,
    label: "Schedule",
    icon: "calendar",
    link: "/mySchedule",
    role: "",
  },
];

export const staffSideBarData = [
  {
    index: 0,
    label: "Dashboard",
    icon: "home",
    link: "/",
    role: "",
  },
  {
    index: 1,
    label: "Student Management",
    icon: "student",
    link: "/students",
    role: "studentMan",
  },
  {
    index: 2,
    label: "Student Grades",
    icon: "student",
    link: "/studentGrades",
    role: "studentGrade",
  },
  {
    index: 3,
    label: "Student Registration",
    icon: "student",
    link: "/studentDepReg",
    role: "studentDepReg",
  },
  {
    index: 4,
    label: "Student Registrations",
    icon: "student",
    link: "/studentReg",
    role: "studentReg",
  },
  {
    index: 5,
    label: "Student Attendance",
    icon: "plans",
    link: "/attendance",
    role: "attendance",
  },
  {
    index: 6,
    label: "Grade Management",
    icon: "student",
    link: "/depGrade",
    role: "depGradeManagement",
  },
  {
    index: 7,
    label: "Grade Management",
    icon: "student",
    link: "/deanGrade",
    role: "deanGradeManagement",
  },
  {
    index: 8,
    label: "Staff Management",
    icon: "staff",
    link: "/staff",
    role: "staffMan",
  },
  {
    index: 9,
    label: "Course Management",
    icon: "book",
    link: "/course",
    role: "courseMan",
  },
  {
    index: 10,
    label: "Curriculum Management",
    icon: "plans",
    link: "/curriculum",
    role: "courseMan",
  },
  {
    index: 11,
    label: "Department Management",
    icon: "building",
    link: "/department",
    role: "departmentMan",
  },
  {
    index: 12,
    label: "Room Management",
    icon: "room",
    link: "/room",
    role: "roomMan",
  },
  {
    index: 13,
    label: "Semester Management",
    icon: "semester",
    link: "/semester",
    role: "semesterMan",
  },
  {
    index: 14,
    label: "Calendar",
    icon: "calendar",
    link: "/calendar",
    role: "",
  },
];

