


### hi 
GET http://localhost:4000/attendance/hi
Content-Type:  application/json

### register

POST http://localhost:8000/attendance/new
Content-Type:  application/json

{
    "course_id":"66658dc0c08179a1fd83af99",
	"instructor_id":"6627d083bc65aace1ba4c794",
	"date":"2024-09-09",
	"attendance":[
		{
			"student_id":"66604076d43809540cc7e7ee",
			"status":"Absent"
			
},
		{
				"student_id":"666591c19eec88796a7461a5",
			"status":"Absent"
			
		}
	]
}




### Get Instructor Attendance
POST http://localhost:6000/attendance/instructor
Content-Type:  application/json

{
   	"course_id":"662802ac728d90164b677588",
	"instructor_id":"6627f3543267383b7d6046e6"
}

### edit
PATCH  http://localhost:6000/attendance/attendance
Content-Type:  application/json

{
	"attendance":[
		{
			"attendance_id":"66637547f851f1dad440e0e1",
			"attendances":[
				{
					"status":"Absent",
					"date" : "2024-09-09",
					"_id" : "66659f7fce8463afa0df0ab8"
				}
			]
			
}
		 
	]
}
### Get stud Attendance
POST http://localhost:2000/attendance/student
Content-Type:  application/json

{
   	"course_id":"6646ed90eff03b65bce49e96",
	"student_id":"66604b63da877f8869719ae7"
}

### delete attendance

DELETE  http://localhost:6000/attendance
Content-Type:  application/json

{
    "course_id":"662802ac728d90164b677588",
	"instructor_id":"6627f3543267383b7d6046e6",
	"date":"2024-09-09"
}

