POST http://localhost:3000/user/student/addDrop/6646788517b2c61fd5e52d84 
Content-Type:  application/json

{
   "add" : ["662802ac728d90164b677588" ,"664b13d72fa1ab9ef543688c"  ]  ,
   "drop" : ["663a03d879c454a6075ec31d"]
}
### to accept or reject 
POST http://localhost:3000/user/student/stausUpdate
Content-Type:  application/json

{
  "addDrop_id" : "664b2a67ca340acae975f11d",
  "status" : "Accept",
  "assignSec" : [
    //{"course_id" : "662802ac728d90164b677588" , "section_id" : "66486b2d16fac6e8375feab0"},
    {"course_id" : "664b13d72fa1ab9ef543688c" , "section_id" : "66486b2d16fac6e8375feab0"}
  ]
}
###
GET  http://localhost:3000/user/student/addDrop?skip=0&limit=2&status=pending
Content-Type:  application/json

 