## the params are temp should be fetched from auth
### 13 get list of enrolled courses student id 
GET  http://localhost:3000/user/student/courses/6646788517b2c61fd5e52d85
Content-Type:  application/json
### 13 get list of courses we can add 
GET  http://localhost:3000/user/student/addcourses/6646788517b2c61fd5e52d84
Content-Type:  application/json

### 14 student send list of courses student id
POST http://localhost:3000/user/student/addDrop/6646788517b2c61fd5e52d84
Content-Type:  application/json

{
   "add" : ["662802ac728d90164b677588" ]  ,
   "drop" : [ ]
}
### 15 department : fetch add and drop requests should use auth to get depid 
GET  http://localhost:3000/user/student/addDrop?skip=0&limit=10&status=pending
Content-Type:  application/json
### get the number course id 
GET   http://localhost:3000/user/student/numberofstudent/662802ac728d90164b677588
Content-Type:  application/json
### 16 department : accept or reject 
POST http://localhost:3000/user/student/stausUpdate
Content-Type:  application/json

{
  "addDrop_id" : "666242d40217c188336ce84c",
  "status" : "Accept",
  "assignSec" : [
    {"course_id" : "662802ac728d90164b677588" , "section_id" : "665cc8fd8191e76e0532e368"}
    //{"course_id" : "664b13d72fa1ab9ef543688c" , "section_id" : "665cc8fd8191e76e0532e368"}
  ]
}
### 17 registrar : get accepted req 
GET  http://localhost:3000/user/student/addDrop?skip=0&limit=2&status=Accepted
Content-Type:  application/json
### 18 registrar : accept or reject 
POST http://localhost:3000/user/student/stausUpdateRegistrar
Content-Type:  application/json

{
  "addDrop_id" : "665f0191ec73504a0ad4c78c",
  "status" : "accept"
}
### 17 dept : get rejected req from registrar
GET  http://localhost:3000/user/student/addDrop?skip=0&limit=2&registrarStatus=rejected
Content-Type:  application/json

### assing teacher to sec 
POST http://localhost:3000/assignment/register
Content-Type:  application/json

{
  "course_id": "662802ac728d90164b677588",
  "section_id":  "665cc8fd8191e76e0532e368",
  "instructor_id" : "664217adf8b1cf7706c8c48c" ,
  "Lab_Lec" : "lecccm",
  "year" :1,
  "semester" : 1
}

## lab lec inst if assigned no of student updated current year and sem
### 
GET  http://localhost:3000/assignment/course?id=662802ac728d90164b677588&year=1&semester=1
Content-Type:  application/json

### 
GET  http://localhost:3000/assignment/course?id=662802ac728d90164b677588&&year=1&semester=1&sections=true
Content-Type:  application/json

 
### assign teacher 
PATCH  http://localhost:3000/assignment/6660153088ec2ceb7defb8b0
Content-Type:  application/json

{
  "instructor_id" : "664217adf8b1cf7706c8c48c"
}

### get curriculum
GET  http://localhost:3000/curriculum/spec?id=664217adf8b1cf7706c8c48c&year=1&semester=1&type=Undergraduate
Content-Type:  application/json

### get staff by depid

GET  http://localhost:3000/user/staff/dept/663646030666c2aea17b217c
Content-Type:  application/json
### get all staffs
GET  http://localhost:3000/user/staff/all 
Content-Type:  application/json

### create a section
POST  http://localhost:3000/section/create
Content-Type:  application/json

{
  "name" : "m",
  "year"  : 1 ,
  "semester" : 1
}

### get students list wiht seciton
POST http://localhost:3000/assignment/teacher
Content-Type:  application/json

{
  "instructor_id" : "664217adf8b1cf7706c8c48c",
  "course_id":"662802ac728d90164b677588"
}

####
POST  http://localhost:3000/user/student/test
Content-Type:  application/json

{
    "department":"663646030666c2aea17b217c",
    "year":1,
    "semester":1,
    "max":2,
    "type" : "Undergraduate"
}