POST http://localhost:3000/course/create 
Content-Type:  application/json

{
  "name": "jh"
}
### fetch based on dep 
GET  http://localhost:3000/course 
Content-Type:  application/json

 
### find by id 
GET  http://localhost:3000/course/66333884b2387b39d3a9bf0b 
Content-Type:  application/json

### update 
PATCH  http://localhost:3000/course/66333884b2387b39d3a9bf0b  
Content-Type:  application/json

{
  "name": "new name"
}
### delete 
DELETE   http://localhost:3000/course/66333884b2387b39d3a9bf0b 
Content-Type:  application/json

### Department 

### create dept 
POST http://localhost:3000/department/create 
Content-Type:  application/json

{
  "name": "new dept"
}
### get dept
GET  http://localhost:3000/department/6633446ee8182ca5eb01630e
Content-Type:  application/json

### fetch based on dep 
GET  http://localhost:3000/department 
Content-Type:  application/json

### update 
PATCH  http://localhost:3000/department/6633446ee8182ca5eb01630e  
Content-Type:  application/json

{
  "name": "old dept"
}
### delete 
DELETE   http://localhost:3000/department/6633465eb9f18a480d1802ae 
Content-Type:  application/json



### Curriculum 

### create curr
POST http://localhost:3000/curriculum/create 
Content-Type:  application/json

{
  "name": "new curr",
   "courses" : [
        {"courseId": "6633548832ad25537ba63d13" , 
        "semester" : 2}
    ]
}
### get curr
GET  http://localhost:3000/curriculum/66336dc4050d56f693de67d5
Content-Type:  application/json

### fetch based on dep 
GET  http://localhost:3000/curriculum 
Content-Type:  application/json

### update 
PATCH  http://localhost:3000/curriculum/6633548832ad25537ba63d13  
Content-Type:  application/json

{
  "name": "old"
}
### delete 
DELETE   http://localhost:3000/curriculum/66335af651f5b3865542d60e 
Content-Type:  application/json
### update cur course 
PATCH  http://localhost:3000/curriculum/addcourse/66336dc4050d56f693de67d5  
Content-Type:  application/json

{
    "courses" : [
        {"courseId": "6633548832ad25537ba63d12" , 
        "semester" : 2},
         {"courseId": "6633548832ad25537ba63d15" , 
        "semester" : 2}
    ]
  
}
### rmv crs crc
DELETE http://localhost:3000/curriculum/deleteCourses/66336dc4050d56f693de67d5  
Content-Type:  application/json

{
    "courses" : [
         "6633548832ad25537ba63d15" 
    ]
  
}